"""add_base_point_value_to_card_catalog

Revision ID: 0f6a6ab68af5
Revises: 1f92c04d01c2
Create Date: 2026-05-31 19:58:32.237250
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '0f6a6ab68af5'
down_revision: Union[str, None] = '1f92c04d01c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_catalogs', sa.Column('base_point_value', sa.Numeric(precision=6, scale=4), nullable=False, server_default='1.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_catalogs', 'base_point_value')
    # ### end Alembic commands ###