"""Add behavioral memory

Revision ID: 124ad47b82e6
Revises: 641351fc6835
Create Date: 2026-05-27 01:53:55.377567
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '124ad47b82e6'
down_revision: Union[str, None] = '641351fc6835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_behavior_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_card_id', sa.Uuid(), nullable=True),
    sa.Column('selected_card_id', sa.Uuid(), nullable=False),
    sa.Column('personality_at_time', sa.VARCHAR(), nullable=False),
    sa.Column('was_followed', sa.Boolean(), nullable=False),
    sa.Column('override_delta_value', sa.Numeric(), nullable=True),
    sa.Column('override_reason', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommended_card_id'], ['user_cards.id'], ),
    sa.ForeignKeyConstraint(['selected_card_id'], ['user_cards.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_behavior_records_transaction_id'), 'recommendation_behavior_records', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_recommendation_behavior_records_user_id'), 'recommendation_behavior_records', ['user_id'], unique=False)
    
    op.alter_column('optimization_personality_profiles', 'confidence_score',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="CASE WHEN confidence_score = 'High' THEN 1.0 ELSE 0.5 END::double precision")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('optimization_personality_profiles', 'confidence_score',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###