"""Initial schema

Revision ID: 1a741499b19a
Revises: 
Create Date: 2026-06-14 00:58:55.984580
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '1a741499b19a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_extraction_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('schema_mapping', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_extraction_templates_bank_name'), 'bank_extraction_templates', ['bank_name'], unique=False)
    op.create_table('benchmark_datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_catalogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('normalized_card_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('joining_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_waiver_spend_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('base_point_value', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reward_rules_json', sa.JSON(), nullable=True),
    sa.Column('milestones_json', sa.JSON(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_catalogs_bank_name'), 'card_catalogs', ['bank_name'], unique=False)
    op.create_index(op.f('ix_card_catalogs_card_name'), 'card_catalogs', ['card_name'], unique=False)
    op.create_index(op.f('ix_card_catalogs_normalized_card_key'), 'card_catalogs', ['normalized_card_key'], unique=True)
    op.create_table('merchant_pending_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_input', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('suggested_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('merchant_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('mcc_hint', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('is_known_brand', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('approved_merchant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_pending_review_status'), 'merchant_pending_review', ['status'], unique=False)
    op.create_table('merchant_resolution_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_input', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('normalized_input', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('resolution_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('fuzzy_score', sa.Float(), nullable=True),
    sa.Column('llm_called', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_resolution_metrics_resolution_type'), 'merchant_resolution_metrics', ['resolution_type'], unique=False)
    op.create_index(op.f('ix_merchant_resolution_metrics_resolved_at'), 'merchant_resolution_metrics', ['resolved_at'], unique=False)
    op.create_index('ix_resolution_metrics_type_date', 'merchant_resolution_metrics', ['resolution_type', 'resolved_at'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('merchant_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('mcc_hint', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('normalized_tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('aliases_list', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_canonical_name'), 'merchants', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_merchants_category'), 'merchants', ['category'], unique=False)
    op.create_index('ix_merchants_category_idx', 'merchants', ['category'], unique=False)
    op.create_index(op.f('ix_merchants_merchant_type'), 'merchants', ['merchant_type'], unique=False)
    op.create_index('ix_merchants_merchant_type_idx', 'merchants', ['merchant_type'], unique=False)
    op.create_index('ix_merchants_normalized_tokens_gin', 'merchants', ['normalized_tokens'], unique=False, postgresql_using='gin')
    op.create_table('prompt_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rule_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rule_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reward_rules_card_active', 'reward_rules', ['card_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_reward_rules_card_id'), 'reward_rules', ['card_id'], unique=False)
    op.create_index('ix_reward_rules_card_priority', 'reward_rules', ['card_id', 'priority'], unique=False)
    op.create_index('ix_reward_rules_config_gin', 'reward_rules', ['rule_config'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_reward_rules_is_active'), 'reward_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_reward_rules_priority'), 'reward_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_reward_rules_rule_type'), 'reward_rules', ['rule_type'], unique=False)
    op.create_table('search_cache',
    sa.Column('query_hash', sa.String(), nullable=False),
    sa.Column('resolved_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('query_hash')
    )
    op.create_index('ix_search_cache_expires', 'search_cache', ['expires_at'], unique=False)
    op.create_table('search_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('resolution_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_sessions_intent_type', 'search_sessions', ['intent_type'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_card_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_merchant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', name='currency'), nullable=False),
    sa.Column('payment_mode', sa.Enum('ONLINE', 'OFFLINE', 'CONTACTLESS', 'UPI', 'INTERNATIONAL', 'ANY', name='paymentmode'), nullable=False),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'REFUND', 'REVERSAL', 'FEE', 'EMI', name='transactiontype'), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('statement_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'REVERSED', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uix_user_id_idempotency_key')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_external_reference'), 'transactions', ['external_reference'], unique=False)
    op.create_index(op.f('ix_transactions_normalized_merchant'), 'transactions', ['normalized_merchant'], unique=False)
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_card_id'), 'transactions', ['user_card_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('card_catalog_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_catalog_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('annual_fee', sa.Float(), nullable=True),
    sa.Column('joining_fee', sa.Float(), nullable=True),
    sa.Column('reward_rate', sa.Float(), nullable=True),
    sa.Column('benefit_metadata', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('published_by_admin_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['card_catalog_id'], ['card_catalogs.id'], ),
    sa.ForeignKeyConstraint(['published_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_catalog_versions_card_catalog_id'), 'card_catalog_versions', ['card_catalog_id'], unique=False)
    op.create_table('card_ingestion_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_catalog_id', sa.Uuid(), nullable=True),
    sa.Column('card_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('review_priority', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('confidence_score_avg', sa.Float(), nullable=False),
    sa.Column('verified_fields_count', sa.Integer(), nullable=False),
    sa.Column('conflicts_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_catalog_id'], ['card_catalogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_ingestion_sessions_card_catalog_id'), 'card_ingestion_sessions', ['card_catalog_id'], unique=False)
    op.create_table('card_monitoring',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('card_url', sa.Text(), nullable=False),
    sa.Column('last_seen_hash', sa.String(length=64), nullable=False),
    sa.Column('stored_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card_catalogs.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('evaluation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('total_benchmarks', sa.Integer(), nullable=False),
    sa.Column('completed_benchmarks', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['benchmark_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_jobs_dataset_id'), 'evaluation_jobs', ['dataset_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('calculated_reward', sa.Float(), nullable=False),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calculation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card_catalogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_calculation_id'), 'feedback', ['calculation_id'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('insight_suppressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('insight_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('insight_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novelty_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_shown_at', sa.DateTime(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('cooldown_expires_at', sa.DateTime(), nullable=True),
    sa.Column('suppression_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_suppressions_insight_category'), 'insight_suppressions', ['insight_category'], unique=False)
    op.create_index(op.f('ix_insight_suppressions_insight_hash'), 'insight_suppressions', ['insight_hash'], unique=False)
    op.create_index(op.f('ix_insight_suppressions_novelty_group'), 'insight_suppressions', ['novelty_group'], unique=False)
    op.create_index(op.f('ix_insight_suppressions_period'), 'insight_suppressions', ['period'], unique=False)
    op.create_index(op.f('ix_insight_suppressions_scope'), 'insight_suppressions', ['scope'], unique=False)
    op.create_index(op.f('ix_insight_suppressions_user_id'), 'insight_suppressions', ['user_id'], unique=False)
    op.create_table('merchant_alias_learning',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('normalized_alias', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias', 'merchant_id', name='uq_alias_learning_norm_merchant')
    )
    op.create_index(op.f('ix_merchant_alias_learning_alias'), 'merchant_alias_learning', ['alias'], unique=False)
    op.create_index(op.f('ix_merchant_alias_learning_merchant_id'), 'merchant_alias_learning', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_alias_learning_normalized_alias'), 'merchant_alias_learning', ['normalized_alias'], unique=False)
    op.create_table('merchant_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('raw_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('normalized_tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'normalized_name', name='uq_alias_merchant_normalized')
    )
    op.create_index(op.f('ix_merchant_aliases_merchant_id'), 'merchant_aliases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_aliases_normalized_name'), 'merchant_aliases', ['normalized_name'], unique=False)
    op.create_index('ix_merchant_aliases_normalized_tokens_gin', 'merchant_aliases', ['normalized_tokens'], unique=False, postgresql_using='gin')
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('optimization_personality_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('active_personality', sa.Enum('MAXIMIZE_REWARDS', 'TRAVEL_OPTIMIZATION', 'FEE_MINIMIZATION', 'BALANCED_INTELLIGENCE', 'WALLET_SIMPLICITY', name='optimizationpersonality'), nullable=False),
    sa.Column('is_inferred', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_personality_profiles_user_id'), 'optimization_personality_profiles', ['user_id'], unique=True)
    op.create_table('portfolio_evolution_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=False),
    sa.Column('value_density', sa.Float(), nullable=False),
    sa.Column('redundancy_score', sa.Float(), nullable=False),
    sa.Column('fee_efficiency_score', sa.Float(), nullable=False),
    sa.Column('strategic_alignment_score', sa.Float(), nullable=False),
    sa.Column('primary_narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strategy_reflections', sa.JSON(), nullable=True),
    sa.Column('evolution_observations', sa.JSON(), nullable=True),
    sa.Column('topology_insights', sa.JSON(), nullable=True),
    sa.Column('ai_narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('narrative_context_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('narrative_context_json', sa.JSON(), nullable=True),
    sa.Column('narrative_generated_at', sa.DateTime(), nullable=True),
    sa.Column('narrative_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('narrative_prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('narrative_generation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_evolution_snapshots_snapshot_date'), 'portfolio_evolution_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_portfolio_evolution_snapshots_user_id'), 'portfolio_evolution_snapshots', ['user_id'], unique=False)
    op.create_table('recommendation_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top_card_id', sa.Uuid(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_audits_id'), 'recommendation_audits', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_audits_user_id'), 'recommendation_audits', ['user_id'], unique=False)
    op.create_table('search_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['search_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_events_session_id', 'search_events', ['session_id'], unique=False)
    op.create_index('ix_search_events_type', 'search_events', ['event_type'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_catalog_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('checksum_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_catalog_id'], ['card_catalogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_card_catalog_id'), 'source_documents', ['card_catalog_id'], unique=False)
    op.create_index(op.f('ix_source_documents_checksum_sha256'), 'source_documents', ['checksum_sha256'], unique=False)
    op.create_table('user_behavioral_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('archetypes', sa.JSON(), nullable=True),
    sa.Column('improving_categories', sa.JSON(), nullable=True),
    sa.Column('stagnant_categories', sa.JSON(), nullable=True),
    sa.Column('card_adoption_rates', sa.JSON(), nullable=True),
    sa.Column('overall_coachability_score', sa.Float(), nullable=False),
    sa.Column('last_calibrated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_behavioral_profiles_user_id'), 'user_behavioral_profiles', ['user_id'], unique=True)
    op.create_table('user_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_catalog_id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_4_digits', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('network_override', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('billing_date', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Integer(), nullable=False),
    sa.Column('fee_cycle_start_date', sa.Date(), nullable=True),
    sa.Column('annual_fee_debit_date', sa.Date(), nullable=True),
    sa.Column('user_override_annual_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('user_override_fee_waiver_threshold', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fee_override_updated_at', sa.DateTime(), nullable=True),
    sa.Column('fee_override_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('card_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_catalog_id'], ['card_catalogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cards_card_catalog_id'), 'user_cards', ['card_catalog_id'], unique=False)
    op.create_index(op.f('ix_user_cards_user_id'), 'user_cards', ['user_id'], unique=False)
    op.create_table('card_ingestion_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_importance', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('extracted_value', sa.JSON(), nullable=True),
    sa.Column('verification_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['card_ingestion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_ingestion_fields_session_id'), 'card_ingestion_fields', ['session_id'], unique=False)
    op.create_table('extraction_benchmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_by_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['benchmark_datasets.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_benchmarks_dataset_id'), 'extraction_benchmarks', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_extraction_benchmarks_document_id'), 'extraction_benchmarks', ['document_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prompt_template_id', sa.Uuid(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_document_id'), 'extraction_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_extraction_runs_prompt_template_id'), 'extraction_runs', ['prompt_template_id'], unique=False)
    op.create_table('recommendation_behavior_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_card_id', sa.Uuid(), nullable=True),
    sa.Column('selected_card_id', sa.Uuid(), nullable=False),
    sa.Column('personality_at_time', sa.Enum('MAXIMIZE_REWARDS', 'TRAVEL_OPTIMIZATION', 'FEE_MINIMIZATION', 'BALANCED_INTELLIGENCE', 'WALLET_SIMPLICITY', name='optimizationpersonality'), nullable=False),
    sa.Column('was_followed', sa.Boolean(), nullable=False),
    sa.Column('override_delta_value', sa.Numeric(), nullable=True),
    sa.Column('override_reason', sa.Enum('PERSONAL_PREFERENCE', 'BUILDING_MILESTONE', 'SIMPLIFYING_WALLET', 'TEMPORARY_CHOICE', 'AVOIDING_ANNUAL_FEE', name='overridereason'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommended_card_id'], ['user_cards.id'], ),
    sa.ForeignKeyConstraint(['selected_card_id'], ['user_cards.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_behavior_records_transaction_id'), 'recommendation_behavior_records', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_recommendation_behavior_records_user_id'), 'recommendation_behavior_records', ['user_id'], unique=False)
    op.create_table('source_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_chunks_checksum'), 'source_chunks', ['checksum'], unique=False)
    op.create_index(op.f('ix_source_chunks_document_id'), 'source_chunks', ['document_id'], unique=False)
    op.create_table('transaction_optimization_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('actual_card_id', sa.Uuid(), nullable=True),
    sa.Column('recommended_card_id', sa.Uuid(), nullable=True),
    sa.Column('adoption_status', sa.Enum('ADOPTED', 'IGNORED', 'PARTIAL', 'PENDING', name='adoptionstatus'), nullable=True),
    sa.Column('estimated_reward_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('recommendation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actual_card_id'], ['user_cards.id'], ),
    sa.ForeignKeyConstraint(['recommended_card_id'], ['user_cards.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_optimization_records_transaction_id'), 'transaction_optimization_records', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transaction_optimization_records_user_id'), 'transaction_optimization_records', ['user_id'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('benchmark_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prompt_template_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_template_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_value', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evaluator_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('error_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_severity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['extraction_benchmarks.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['benchmark_datasets.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_runs_benchmark_id'), 'benchmark_runs', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_benchmark_runs_dataset_id'), 'benchmark_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_benchmark_runs_extraction_run_id'), 'benchmark_runs', ['extraction_run_id'], unique=False)
    op.create_index(op.f('ix_benchmark_runs_prompt_template_id'), 'benchmark_runs', ['prompt_template_id'], unique=False)
    op.create_table('card_field_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('evidence_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('confidence_contribution', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['card_ingestion_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_field_sources_field_id'), 'card_field_sources', ['field_id'], unique=False)
    op.create_table('extracted_field_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('candidate_value', sa.JSON(), nullable=True),
    sa.Column('admin_corrected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('retrieval_rank', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['source_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_field_candidates_extraction_run_id'), 'extracted_field_candidates', ['extraction_run_id'], unique=False)
    op.create_table('ingestion_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=True),
    sa.Column('modified_value', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['card_ingestion_fields.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['card_ingestion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_audit_logs_session_id'), 'ingestion_audit_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_audit_logs_session_id'), table_name='ingestion_audit_logs')
    op.drop_table('ingestion_audit_logs')
    op.drop_index(op.f('ix_extracted_field_candidates_extraction_run_id'), table_name='extracted_field_candidates')
    op.drop_table('extracted_field_candidates')
    op.drop_index(op.f('ix_card_field_sources_field_id'), table_name='card_field_sources')
    op.drop_table('card_field_sources')
    op.drop_index(op.f('ix_benchmark_runs_prompt_template_id'), table_name='benchmark_runs')
    op.drop_index(op.f('ix_benchmark_runs_extraction_run_id'), table_name='benchmark_runs')
    op.drop_index(op.f('ix_benchmark_runs_dataset_id'), table_name='benchmark_runs')
    op.drop_index(op.f('ix_benchmark_runs_benchmark_id'), table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_index(op.f('ix_transaction_optimization_records_user_id'), table_name='transaction_optimization_records')
    op.drop_index(op.f('ix_transaction_optimization_records_transaction_id'), table_name='transaction_optimization_records')
    op.drop_table('transaction_optimization_records')
    op.drop_index(op.f('ix_source_chunks_document_id'), table_name='source_chunks')
    op.drop_index(op.f('ix_source_chunks_checksum'), table_name='source_chunks')
    op.drop_table('source_chunks')
    op.drop_index(op.f('ix_recommendation_behavior_records_user_id'), table_name='recommendation_behavior_records')
    op.drop_index(op.f('ix_recommendation_behavior_records_transaction_id'), table_name='recommendation_behavior_records')
    op.drop_table('recommendation_behavior_records')
    op.drop_index(op.f('ix_extraction_runs_prompt_template_id'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_document_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_extraction_benchmarks_document_id'), table_name='extraction_benchmarks')
    op.drop_index(op.f('ix_extraction_benchmarks_dataset_id'), table_name='extraction_benchmarks')
    op.drop_table('extraction_benchmarks')
    op.drop_index(op.f('ix_card_ingestion_fields_session_id'), table_name='card_ingestion_fields')
    op.drop_table('card_ingestion_fields')
    op.drop_index(op.f('ix_user_cards_user_id'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_card_catalog_id'), table_name='user_cards')
    op.drop_table('user_cards')
    op.drop_index(op.f('ix_user_behavioral_profiles_user_id'), table_name='user_behavioral_profiles')
    op.drop_table('user_behavioral_profiles')
    op.drop_index(op.f('ix_source_documents_checksum_sha256'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_card_catalog_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index('ix_search_events_type', table_name='search_events')
    op.drop_index('ix_search_events_session_id', table_name='search_events')
    op.drop_table('search_events')
    op.drop_index(op.f('ix_recommendation_audits_user_id'), table_name='recommendation_audits')
    op.drop_index(op.f('ix_recommendation_audits_id'), table_name='recommendation_audits')
    op.drop_table('recommendation_audits')
    op.drop_index(op.f('ix_portfolio_evolution_snapshots_user_id'), table_name='portfolio_evolution_snapshots')
    op.drop_index(op.f('ix_portfolio_evolution_snapshots_snapshot_date'), table_name='portfolio_evolution_snapshots')
    op.drop_table('portfolio_evolution_snapshots')
    op.drop_index(op.f('ix_optimization_personality_profiles_user_id'), table_name='optimization_personality_profiles')
    op.drop_table('optimization_personality_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_merchant_aliases_normalized_tokens_gin', table_name='merchant_aliases', postgresql_using='gin')
    op.drop_index(op.f('ix_merchant_aliases_normalized_name'), table_name='merchant_aliases')
    op.drop_index(op.f('ix_merchant_aliases_merchant_id'), table_name='merchant_aliases')
    op.drop_table('merchant_aliases')
    op.drop_index(op.f('ix_merchant_alias_learning_normalized_alias'), table_name='merchant_alias_learning')
    op.drop_index(op.f('ix_merchant_alias_learning_merchant_id'), table_name='merchant_alias_learning')
    op.drop_index(op.f('ix_merchant_alias_learning_alias'), table_name='merchant_alias_learning')
    op.drop_table('merchant_alias_learning')
    op.drop_index(op.f('ix_insight_suppressions_user_id'), table_name='insight_suppressions')
    op.drop_index(op.f('ix_insight_suppressions_scope'), table_name='insight_suppressions')
    op.drop_index(op.f('ix_insight_suppressions_period'), table_name='insight_suppressions')
    op.drop_index(op.f('ix_insight_suppressions_novelty_group'), table_name='insight_suppressions')
    op.drop_index(op.f('ix_insight_suppressions_insight_hash'), table_name='insight_suppressions')
    op.drop_index(op.f('ix_insight_suppressions_insight_category'), table_name='insight_suppressions')
    op.drop_table('insight_suppressions')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_calculation_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_evaluation_jobs_dataset_id'), table_name='evaluation_jobs')
    op.drop_table('evaluation_jobs')
    op.drop_table('card_monitoring')
    op.drop_index(op.f('ix_card_ingestion_sessions_card_catalog_id'), table_name='card_ingestion_sessions')
    op.drop_table('card_ingestion_sessions')
    op.drop_index(op.f('ix_card_catalog_versions_card_catalog_id'), table_name='card_catalog_versions')
    op.drop_table('card_catalog_versions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_card_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_normalized_merchant'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_search_sessions_intent_type', table_name='search_sessions')
    op.drop_table('search_sessions')
    op.drop_index('ix_search_cache_expires', table_name='search_cache')
    op.drop_table('search_cache')
    op.drop_index(op.f('ix_reward_rules_rule_type'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_priority'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_is_active'), table_name='reward_rules')
    op.drop_index('ix_reward_rules_config_gin', table_name='reward_rules', postgresql_using='gin')
    op.drop_index('ix_reward_rules_card_priority', table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_card_id'), table_name='reward_rules')
    op.drop_index('ix_reward_rules_card_active', table_name='reward_rules')
    op.drop_table('reward_rules')
    op.drop_table('prompt_templates')
    op.drop_index('ix_merchants_normalized_tokens_gin', table_name='merchants', postgresql_using='gin')
    op.drop_index('ix_merchants_merchant_type_idx', table_name='merchants')
    op.drop_index(op.f('ix_merchants_merchant_type'), table_name='merchants')
    op.drop_index('ix_merchants_category_idx', table_name='merchants')
    op.drop_index(op.f('ix_merchants_category'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_canonical_name'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index('ix_resolution_metrics_type_date', table_name='merchant_resolution_metrics')
    op.drop_index(op.f('ix_merchant_resolution_metrics_resolved_at'), table_name='merchant_resolution_metrics')
    op.drop_index(op.f('ix_merchant_resolution_metrics_resolution_type'), table_name='merchant_resolution_metrics')
    op.drop_table('merchant_resolution_metrics')
    op.drop_index(op.f('ix_merchant_pending_review_status'), table_name='merchant_pending_review')
    op.drop_table('merchant_pending_review')
    op.drop_index(op.f('ix_card_catalogs_normalized_card_key'), table_name='card_catalogs')
    op.drop_index(op.f('ix_card_catalogs_card_name'), table_name='card_catalogs')
    op.drop_index(op.f('ix_card_catalogs_bank_name'), table_name='card_catalogs')
    op.drop_table('card_catalogs')
    op.drop_table('benchmark_datasets')
    op.drop_index(op.f('ix_bank_extraction_templates_bank_name'), table_name='bank_extraction_templates')
    op.drop_table('bank_extraction_templates')
    # ### end Alembic commands ###