"""Add Phase 3D fields

Revision ID: 1e6618c89401
Revises: 1a741499b19a
Create Date: 2026-06-14 01:09:55.111990
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '1e6618c89401'
down_revision: Union[str, None] = '1a741499b19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark_datasets', sa.Column('dataset_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('benchmark_runs', sa.Column('retrieved_chunks_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('benchmark_runs', sa.Column('correct_chunk_found', sa.Boolean(), nullable=True))
    op.add_column('prompt_templates', sa.Column('hypothesis', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_templates', 'hypothesis')
    op.drop_column('benchmark_runs', 'correct_chunk_found')
    op.drop_column('benchmark_runs', 'retrieved_chunks_snapshot')
    op.drop_column('benchmark_datasets', 'dataset_type')
    # ### end Alembic commands ###