"""Add change_type and published_rule_id to candidate

Revision ID: 1f92c04d01c2
Revises: 1790d91a77fe
Create Date: 2026-05-30 17:35:34.989511
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '1f92c04d01c2'
down_revision: Union[str, None] = '1790d91a77fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('card_catalogs_normalized_card_key_key'), 'card_catalogs', type_='unique')
    op.create_index(op.f('ix_card_catalogs_normalized_card_key'), 'card_catalogs', ['normalized_card_key'], unique=True)
    op.add_column('card_extraction_candidates', sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='ADD'))
    op.add_column('card_extraction_candidates', sa.Column('published_rule_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_extraction_candidates', 'published_rule_id')
    op.drop_column('card_extraction_candidates', 'change_type')
    op.drop_index(op.f('ix_card_catalogs_normalized_card_key'), table_name='card_catalogs')
    op.create_unique_constraint(op.f('card_catalogs_normalized_card_key_key'), 'card_catalogs', ['normalized_card_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###