"""add Phase 3A extraction models

Revision ID: 3028455440fa
Revises: bbdea00a7ba2
Create Date: 2026-05-29 11:57:09.979153
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '3028455440fa'
down_revision: Union[str, None] = 'bbdea00a7ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_snapshots', sa.Column('raw_llm_response', sa.JSON(), nullable=True))
    op.alter_column('source_text_artifacts', 'raw_text',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_text_artifacts', 'raw_text',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('extraction_snapshots', 'raw_llm_response')
    # ### end Alembic commands ###