"""Add CardMonitoring and json columns to CardCatalog

Revision ID: 41a3cc3eb1cc
Revises: 0f6a6ab68af5
Create Date: 2026-06-04 00:36:10.705783
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '41a3cc3eb1cc'
down_revision: Union[str, None] = '0f6a6ab68af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_monitoring',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('card_url', sa.Text(), nullable=False),
    sa.Column('last_seen_hash', sa.String(length=32), nullable=False),
    sa.Column('stored_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card_catalogs.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.add_column('card_catalogs', sa.Column('reward_rules_json', sa.JSON(), nullable=True))
    op.add_column('card_catalogs', sa.Column('milestones_json', sa.JSON(), nullable=True))
    op.add_column('card_catalogs', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_catalogs', 'is_approved')
    op.drop_column('card_catalogs', 'milestones_json')
    op.drop_column('card_catalogs', 'reward_rules_json')
    op.drop_table('card_monitoring')
    # ### end Alembic commands ###