"""drop_user_agent_from_sessions

Revision ID: 437eaaebb259
Revises: 762bf26dafc4
Create Date: 2026-08-30 23:53:44.018280
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '437eaaebb259'
down_revision: Union[str, None] = '762bf26dafc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_agent', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###