"""Add portfolio evolution snapshot

Revision ID: 52fa158ecb54
Revises: 124ad47b82e6
Create Date: 2026-05-28 00:24:34.658741
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '52fa158ecb54'
down_revision: Union[str, None] = '124ad47b82e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendation_behavior_records', 'personality_at_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('MAXIMIZE_REWARDS', 'TRAVEL_OPTIMIZATION', 'FEE_MINIMIZATION', 'BALANCED_INTELLIGENCE', 'WALLET_SIMPLICITY', name='optimizationpersonality'),
               existing_nullable=False,
               postgresql_using='personality_at_time::optimizationpersonality')
    op.alter_column('recommendation_behavior_records', 'override_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PERSONAL_PREFERENCE', 'BUILDING_MILESTONE', 'SIMPLIFYING_WALLET', 'TEMPORARY_CHOICE', 'AVOIDING_ANNUAL_FEE', name='overridereason'),
               existing_nullable=True,
               postgresql_using='override_reason::overridereason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendation_behavior_records', 'override_reason',
               existing_type=sa.Enum('PERSONAL_PREFERENCE', 'BUILDING_MILESTONE', 'SIMPLIFYING_WALLET', 'TEMPORARY_CHOICE', 'AVOIDING_ANNUAL_FEE', name='overridereason'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('recommendation_behavior_records', 'personality_at_time',
               existing_type=sa.Enum('MAXIMIZE_REWARDS', 'TRAVEL_OPTIMIZATION', 'FEE_MINIMIZATION', 'BALANCED_INTELLIGENCE', 'WALLET_SIMPLICITY', name='optimizationpersonality'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###