"""add priority to feedback

Revision ID: 5c960bb692be
Revises: a041be11779d
Create Date: 2026-06-07 20:48:41.047880
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '5c960bb692be'
down_revision: Union[str, None] = 'a041be11779d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='LOW'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###