"""add_card_intelligence_tables

Revision ID: 6141e085b98d
Revises: f14779db9eab
Create Date: 2026-05-29 01:25:23.676530
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '6141e085b98d'
down_revision: Union[str, None] = 'f14779db9eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('REWARD_GUIDE', 'MITC', 'FEES_AND_CHARGES', 'BENEFITS_GUIDE', 'EXCLUSIONS', 'MILESTONE_RULES', 'OFFER_TERMS', 'GENERAL_TERMS', name='carddocumenttype'), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentprocessingstatus'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('checksum_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card_catalogs.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_documents_card_id'), 'card_documents', ['card_id'], unique=False)
    op.create_table('document_ingestion_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentprocessingstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('pipeline_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['card_documents.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_ingestion_jobs_document_id'), 'document_ingestion_jobs', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_ingestion_jobs_document_id'), table_name='document_ingestion_jobs')
    op.drop_table('document_ingestion_jobs')
    op.drop_index(op.f('ix_card_documents_card_id'), table_name='card_documents')
    op.drop_table('card_documents')
    # ### end Alembic commands ###