"""add_affiliate_to_card_catalog

Revision ID: 6abf1497752b
Revises: 437eaaebb259
Create Date: 2026-08-31 23:54:31.373533
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '6abf1497752b'
down_revision: Union[str, None] = '437eaaebb259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_catalogs', sa.Column('affiliate_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    op.add_column('card_catalogs', sa.Column('affiliate_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_catalogs', 'affiliate_active')
    op.drop_column('card_catalogs', 'affiliate_url')
    # ### end Alembic commands ###