"""add_search_models

Revision ID: 8b9bfa7f6206
Revises: a1b2c3d4e5f6
Create Date: 2026-06-12 22:11:56.719152
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '8b9bfa7f6206'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_cache',
    sa.Column('query_hash', sa.String(), nullable=False),
    sa.Column('resolved_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('query_hash')
    )
    op.create_index('ix_search_cache_expires', 'search_cache', ['expires_at'], unique=False)
    op.create_table('search_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('resolution_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_sessions_intent_type', 'search_sessions', ['intent_type'], unique=False)
    op.create_table('search_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['search_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_events_session_id', 'search_events', ['session_id'], unique=False)
    op.create_index('ix_search_events_type', 'search_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_events_type', table_name='search_events')
    op.drop_index('ix_search_events_session_id', table_name='search_events')
    op.drop_table('search_events')
    op.drop_index('ix_search_sessions_intent_type', table_name='search_sessions')
    op.drop_table('search_sessions')
    op.drop_index('ix_search_cache_expires', table_name='search_cache')
    op.drop_table('search_cache')
    # ### end Alembic commands ###