"""add ai narrative fields to portfolio snapshot

Revision ID: 9474feee0fb7
Revises: c4bd4f04fa54
Create Date: 2026-05-28 01:59:46.740223
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = '9474feee0fb7'
down_revision: Union[str, None] = 'c4bd4f04fa54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_evolution_snapshots', sa.Column('ai_narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('portfolio_evolution_snapshots', sa.Column('narrative_context_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('portfolio_evolution_snapshots', sa.Column('narrative_context_json', sa.JSON(), nullable=True))
    op.add_column('portfolio_evolution_snapshots', sa.Column('narrative_generated_at', sa.DateTime(), nullable=True))
    op.add_column('portfolio_evolution_snapshots', sa.Column('narrative_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('portfolio_evolution_snapshots', sa.Column('narrative_prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('portfolio_evolution_snapshots', sa.Column('narrative_generation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_evolution_snapshots', 'narrative_generation_reason')
    op.drop_column('portfolio_evolution_snapshots', 'narrative_prompt_version')
    op.drop_column('portfolio_evolution_snapshots', 'narrative_model')
    op.drop_column('portfolio_evolution_snapshots', 'narrative_generated_at')
    op.drop_column('portfolio_evolution_snapshots', 'narrative_context_json')
    op.drop_column('portfolio_evolution_snapshots', 'narrative_context_hash')
    op.drop_column('portfolio_evolution_snapshots', 'ai_narrative')
    # ### end Alembic commands ###