"""add last_4_digits to user_cards

Revision ID: 990a5a6746b4
Revises: dfd00a1a401d
Create Date: 2026-06-07 23:29:37.761647
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '990a5a6746b4'
down_revision: Union[str, None] = 'dfd00a1a401d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cards', sa.Column('last_4_digits', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cards', 'last_4_digits')
    # ### end Alembic commands ###