"""add_recommendation_audit

Revision ID: a041be11779d
Revises: f073a8056a8e
Create Date: 2026-06-07 19:50:28.986279
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'a041be11779d'
down_revision: Union[str, None] = 'f073a8056a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top_card_id', sa.Uuid(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_audits_id'), 'recommendation_audits', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_audits_user_id'), 'recommendation_audits', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_audits_user_id'), table_name='recommendation_audits')
    op.drop_index(op.f('ix_recommendation_audits_id'), table_name='recommendation_audits')
    op.drop_table('recommendation_audits')
    # ### end Alembic commands ###