"""add user override fee waiver threshold

Revision ID: a80befd650d6
Revises: 50d246692095
Create Date: 2026-05-26 19:55:04.296956
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'a80befd650d6'
down_revision: Union[str, None] = '50d246692095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cards', sa.Column('user_override_fee_waiver_threshold', sa.Numeric(precision=14, scale=2), nullable=True))
    op.drop_constraint(op.f('user_cards_card_catalog_id_fkey'), 'user_cards', type_='foreignkey')
    op.drop_constraint(op.f('user_cards_user_id_fkey'), 'user_cards', type_='foreignkey')
    op.create_foreign_key(None, 'user_cards', 'card_catalogs', ['card_catalog_id'], ['id'])
    op.create_foreign_key(None, 'user_cards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_cards', type_='foreignkey')
    op.drop_constraint(None, 'user_cards', type_='foreignkey')
    op.create_foreign_key(op.f('user_cards_user_id_fkey'), 'user_cards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_cards_card_catalog_id_fkey'), 'user_cards', 'card_catalogs', ['card_catalog_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_cards', 'user_override_fee_waiver_threshold')
    # ### end Alembic commands ###