"""add_extraction_candidates_and_versions

Revision ID: bbdea00a7ba2
Revises: bd869fb232a4
Create Date: 2026-05-29 10:30:16.403510
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'bbdea00a7ba2'
down_revision: Union[str, None] = 'bd869fb232a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###