"""Add network_override to user_cards

Revision ID: bbe16db62ce1
Revises: 990a5a6746b4
Create Date: 2026-06-07 23:48:19.232969
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'bbe16db62ce1'
down_revision: Union[str, None] = '990a5a6746b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cards', sa.Column('network_override', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cards', 'network_override')
    # ### end Alembic commands ###