"""evolve to knowledge sources

Revision ID: bd869fb232a4
Revises: 6141e085b98d
Create Date: 2026-05-29 09:29:55.255819
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'bd869fb232a4'
down_revision: Union[str, None] = '6141e085b98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_knowledge_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('PDF', 'URL', 'HTML', name='knowledgesourcetype'), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sa.Enum('DISCOVERED', 'IMPORTED', 'UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('checksum_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card_catalogs.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_knowledge_sources_card_id'), 'card_knowledge_sources', ['card_id'], unique=False)
    op.create_table('knowledge_ingestion_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'IMPORTED', 'UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('pipeline_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['card_knowledge_sources.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_ingestion_jobs_knowledge_source_id'), 'knowledge_ingestion_jobs', ['knowledge_source_id'], unique=False)
    op.drop_index(op.f('ix_document_ingestion_jobs_document_id'), table_name='document_ingestion_jobs')
    op.drop_table('document_ingestion_jobs')
    op.drop_index(op.f('ix_card_documents_card_id'), table_name='card_documents')
    op.drop_table('card_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_ingestion_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentprocessingstatus'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pipeline_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trigger_source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('logs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('triggered_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['card_documents.id'], name=op.f('document_ingestion_jobs_document_id_fkey')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('document_ingestion_jobs_triggered_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_ingestion_jobs_pkey'))
    )
    op.create_index(op.f('ix_document_ingestion_jobs_document_id'), 'document_ingestion_jobs', ['document_id'], unique=False)
    op.create_table('card_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('REWARD_GUIDE', 'MITC', 'FEES_AND_CHARGES', 'BENEFITS_GUIDE', 'EXCLUSIONS', 'MILESTONE_RULES', 'OFFER_TERMS', 'GENERAL_TERMS', name='carddocumenttype'), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processing_status', postgresql.ENUM('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentprocessingstatus'), autoincrement=False, nullable=False),
    sa.Column('processing_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processing_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processing_error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checksum_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card_catalogs.id'], name=op.f('card_documents_card_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('card_documents_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('card_documents_pkey'))
    )
    op.create_index(op.f('ix_card_documents_card_id'), 'card_documents', ['card_id'], unique=False)
    op.drop_index(op.f('ix_knowledge_ingestion_jobs_knowledge_source_id'), table_name='knowledge_ingestion_jobs')
    op.drop_table('knowledge_ingestion_jobs')
    op.drop_index(op.f('ix_card_knowledge_sources_card_id'), table_name='card_knowledge_sources')
    op.drop_table('card_knowledge_sources')
    # ### end Alembic commands ###