"""add structured narrative arrays to portfolio snapshot

Revision ID: c4bd4f04fa54
Revises: 52fa158ecb54
Create Date: 2026-05-28 01:02:14.637896
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'c4bd4f04fa54'
down_revision: Union[str, None] = '52fa158ecb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_evolution_snapshots', sa.Column('strategy_reflections', sa.JSON(), nullable=True))
    op.add_column('portfolio_evolution_snapshots', sa.Column('evolution_observations', sa.JSON(), nullable=True))
    op.add_column('portfolio_evolution_snapshots', sa.Column('topology_insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_evolution_snapshots', 'topology_insights')
    op.drop_column('portfolio_evolution_snapshots', 'evolution_observations')
    op.drop_column('portfolio_evolution_snapshots', 'strategy_reflections')
    # ### end Alembic commands ###