"""Add annual_fee_debit_date to user_cards

Revision ID: f14779db9eab
Revises: 9474feee0fb7
Create Date: 2026-05-28 23:50:53.634885
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic
revision: str = 'f14779db9eab'
down_revision: Union[str, None] = '9474feee0fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cards', sa.Column('annual_fee_debit_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cards', 'annual_fee_debit_date')
    # ### end Alembic commands ###