"""
Module: backend.models.recommendation_audit
Responsibility: SQLAlchemy model for recommendation audits.
"""

from datetime import datetime, UTC
from typing import Any, Optional
import uuid
from sqlmodel import Field, SQLModel, Column, JSON


class RecommendationAudit(SQLModel, table=True):
    __tablename__ = "recommendation_audits"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        index=True,
        description="calculation_id generated by the engine"
    )
    user_id: uuid.UUID = Field(
        foreign_key="users.id",
        index=True,
        description="The user who requested the recommendation"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC).replace(tzinfo=None),
        description="When this recommendation was generated"
    )
    merchant_name: str = Field(
        description="The merchant name used in the evaluation"
    )
    amount: float = Field(
        description="The transaction amount"
    )
    rule_version: str = Field(
        description="The version of the rules engine used for this calculation"
    )
    top_card_id: Optional[uuid.UUID] = Field(
        default=None,
        description="The ID of the top recommended card, if any"
    )
    request_payload: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(JSON),
        description="The full recommendation request"
    )
    response_payload: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(JSON),
        description="The full optimization response"
    )
